import { createContext } from "react";

const SongContext = createContext({
    currentSong: null,
    setCurrentSong: (currentSong) => {},
    songPlayed: null, 
    setSongPlayed: () => {},
    isPaused: null, 
    setIsPaused: () => {},
    songData: [],
    setSongData: () => {},
    isCreatePlaylistModalOpen: null,
    setIsCreatePlaylistModalOpen: () => {},
    isAddToPlaylistModalOpen: {
        isOpen: false,
        song: null,
    },
    setIsAddToPlaylistModalOpen: () => {},
    currentTime: 0,
    setCurrentTime: () => {},
    duration: 0,
    setDuration: () => {},
    intervalId: null,
    setIntervalId: () => {},
    soundRef: null,  
    setSoundRef: () => {}, 
    playlist: [],
    setPlaylist: ()=>{},
    currentSongIndex: 0,
    setCurrentSongIndex: ()=>{},
    queue: [],
    setQueue:()=>{},
    isQueueModalOpen: null,
    setIsQueueModalOpen: ()=>{},
    volumeIcon: null,
    setVolumeIcon: ()=>{},
    volume: null,
    setVolume: ()=>{},
    isRepeatMode: false,
    setIsRepeatMode: ()=>{},
    isSideVisible: null, 
    setIsSideVisible: ()=>{},
    isLeftPanelOpen: null,
    setIsLeftPanelOpen:()=>{},
    historyData: null, 
    setHistoryData: ()=>{},
    isRegisterAsArtistModalOpen : null,
    setIsRegisterAsArtistModalOpen : ()=>{},
    artistData: null,
    setArtistData: ()=>{},
    isPlaylistPlaying: null, 
    setIsPlaylistPlaying: ()=>{},
    isArtist: null,
    setIsArtist: ()=>{},
    resumeTime: null, 
    setResumeTime:()=>{},
    savedPosition: null, 
    setSavedPosition:()=>{},
});

export default SongContext;
